# Generated by Django 5.2.7 on 2025-11-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время парсинга')),
                ('temperature', models.CharField(max_length=50, verbose_name='Температура')),
                ('description', models.CharField(max_length=255, verbose_name='Описание (ясно/облачно)')),
                ('source_url', models.URLField(verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Данные погоды',
                'verbose_name_plural': 'История погоды',
                'ordering': ['-date'],
            },
        ),
    ]
