# Generated by Django 5.2.7 on 2025-11-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_weatherdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-date'], 'verbose_name': 'Данные погоды', 'verbose_name_plural': 'Данные погоды'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='source_url',
            field=models.URLField(verbose_name='Источник данных'),
        ),
    ]
