# Generated by Django 5.2.7 on 2025-11-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_alter_weatherdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-date'], 'verbose_name': 'Данные о погоде', 'verbose_name_plural': 'Данные о погоде'},
        ),
    ]
