# Generated by Django 5.2.7 on 2025-11-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-date'], 'verbose_name': 'Погода', 'verbose_name_plural': 'История погоды'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='encrypted_media',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='content_type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='encrypted_data',
            field=models.BinaryField(verbose_name='Зашифрованные данные'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file_size',
            field=models.IntegerField(verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='Оригинальное имя'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='source_url',
            field=models.URLField(verbose_name='Источник'),
        ),
    ]
