# Generated by Django 5.2.7 on 2025-11-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_alter_customuser_options_alter_weatherdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-date'], 'verbose_name': 'Данные погоды', 'verbose_name_plural': 'История погоды'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='encrypted_media',
            field=models.BinaryField(blank=True, null=True, verbose_name='Зашифрованные медиафайлы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='content_type',
            field=models.CharField(max_length=100, verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='encrypted_data',
            field=models.BinaryField(verbose_name='Зашифрованные данные файла'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file_size',
            field=models.IntegerField(verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='Оригинальное имя файла'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время парсинга'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание (ясно/облачно)'),
        ),
    ]
